name: Metrics embed
on:
  schedule:
    - cron: "0 */3 * * *"
  push:
    branches:
      - "main"
jobs:
  create-embed:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Include forks in metrics
          repositories_forks: on
          
          # GitHub Personal Token
          token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          # GitHub username
          user: dytroInc
          
          # Timezone used
          config_timezone: Asia/Seoul
          # Use twemojis instead of emojis
          config_twemoji: on

          # Display an isometric view of your commits calendar
          plugin_isocalendar: on

          # Display most used languages metrics
          plugin_languages: on
          # Maximum number of languages to display
          plugin_languages_limit: 0
          # Maximum event age (for recently used section)
          plugin_languages_recent_days: 0
          
          # Display starred topics
          plugin_topics: on
          # Maximum number of topics to display
          plugin_topics_limit: 0
          
          # Display recently starred repositories
          plugin_stars: on
          # Maximum number of stars to display
          plugin_stars_limit: 5
          
          # Display licenses informations
          plugin_licenses: on
          # Display used licenses ratio
          plugin_licenses_ratio: on
          
          # Display coding habits metrics
          plugin_habits: on
          # Number of events to use
          plugin_habits_from: 300
          # Maximum event age
          plugin_habits_days: 31
          # Display coding habits charts based on recent activity
          plugin_habits_charts: on
          
          # Display repository contributors
          plugin_contributors: on
          # Display contributions
          plugin_contributors_contributions: on
          # Sections to display
          plugin_contributors_sections: contributors
          
          # Display follow-up of repositories issues and pull requests
          plugin_followup: on
          
          # Display stargazers metrics
          plugin_stargazers: on
          
          # Display active projects
          plugin_projects: on
          # Maximum number of projects to display
          plugin_projects_limit: 5
          # Display projects descriptions
          plugin_projects_descriptions: on
          
          # Display recent activity
          plugin_activity: on
          # Maximum number of events to display
          plugin_activity_limit: 10
          # Maximum event age
          plugin_activity_days: 0
          # Display events timestamps
          plugin_activity_timestamps: on
          
          # Display achievements
          plugin_achievements: on
          
          # Display notable contributions in organizations
          plugin_notable: on
          # Also display repository name
          plugin_notable_repositories: on
          
          # GitHub discussions metrics
          plugin_discussions: on
          
          # GitHub Community Support metrics
          plugin_support: on
          
          # Display lines of code metrics
          plugin_lines: on

          # Display repositories traffic metrics
          plugin_traffic: on
          
          # Display account or repository introduction
          plugin_introduction: on
          # Display introduction section title
          plugin_introduction_title: on
          
          # Display GitHub Skyline 3D calendar
          plugin_skyline: on
          # Number of frames
          plugin_skyline_frames: 100
          # Image quality
          plugin_skyline_quality: 1.0
